site_name: Chokie
site_description: Welcome to Chokie's blog.
site_author: Chokie
site_dir: 'ura'
copyright: 'Copyright &copy; 2020 Chokie'
nav:
  - Home: index.md
  - Game: game/index.md
  - Anime: anime/index.md
  - Comic: comic/index.md
  - music: music/index.md
  - 表博客: omote/

theme:
  name: cinder

extra:
  social:
    - icon: fontawesome/brands/steam
      link: 'https://steamcommunity.com/id/ZhChokie/'

google_analytics:
  - UA-173124167-1
  - auto