site_name: Chokie
site_url: 'https://chokie-zhang.github.io'
site_description: Welcome to Chokie's blog.
site_author: Chokie
copyright: 'Copyright &copy; 2020 Chokie'
nav:
  - Home: index.md
  - Research: research/index.md
  - Competition: competition/index.md
  - Else: else/index.md
  - 里博客: ura/

theme:
  name: cinder

google_analytics:
  - UA-173124167-1
  - auto